curl --location --request POST 'https://crm.belmar.pro/api/v1/addlead'
   --header 'token: ba67df6a-a17c-476f-8e95-bcdb75ed3958'
   --header 'Content-Type: application/json'
   --data-raw '{
       "firstName" : "dfsd",
       "lastName" : "dfffdfsd",
       "phone" : "2356373",
       "email" : "qw@bs.com",
       "countryCode" : "GB",
       "box_id" : "28",
       "offer_id" : "5",
       "landingUrl" : "www.google.con",
       "ip" : "127.0.0.1",
       "password" : "qwerty12",
"language" : "en",
"clickId" : "",
"quizAnswers" : "",
"custom1" : "",
}'


 curl --location --request POST 'https://crm.belmar.pro/api/v1/getstatuses'
   --header 'token: ba67df6a-a17c-476f-8e95-bcdb75ed3958'
   --header 'Content-Type: application/json'
   --data-raw '{
       "date_from" : "2022-12-01 00:00:00",
       "date_to" : "2022-12-31 23:59:59",
       "page" : 0,
       "limit" : 100
   }'


POST https://crm.belmar.pro/api/v1/getstatuses
token: <token>
Content-Type: application/json

{
       "date_from" : "2022-12-01 00:00:00", // default -30days, max -60days
       "date_to" : "2022-12-31 23:59:59",   // default now
       "page" : 0,                          // default 0
       "limit" : 100                        // default 100, max 500
   }

###



# curl --location --request POST 'https://crm.belmar.pro/api/v1/getstatuses'
#   --header 'token: <token>'
#   --header 'Content-Type: application/json'
#   --data-raw '{
#       "date_from" : "2022-12-01 00:00:00", // default -30days, max -60days
#       "date_to" : "2022-12-31 23:59:59",   // default now
#       "page" : 0,                          // default 0
#       "limit" : 100                        // default 100, max 500
#   }'


POST https://crm.belmar.pro/api/v1/getstatuses
token: <token>
Content-Type: application/json

{
  "date_from": "2022-12-01 00:00:00",
  // default -30days, max -60days
  "date_to": "2022-12-31 23:59:59",
  // default now
  "page": 0,
  // default 0
  "limit": 100
  // default 100, max 500
}

###

